version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
  
  app:
    image: node:18-alpine
    
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
      
  custom:
    image: flanksource/canary-checker:latest