name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true  # Non-blocking - won't prevent merges

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Cache Java dependencies
        uses: actions/cache@v4
        with:
          path: |
            analysis/java/.gradle
            analysis/java/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('analysis/java/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run linting
        run: task lint